predefined_groups:
  small:
    total_cardinals: 5
    cardinal_ids:
    - 224
    - 208
    - 176
    - 233
    - 108
    candidate_ids:
    - 176
    - 224
    elector_ids:
    - 208
    - 233
    - 108
    description: Small group with 5 cardinals and 2 candidates
    ideology_balance:
      progressive: 1
      conservative: 1
      moderate: 3
  medium:
    total_cardinals: 15
    cardinal_ids:
    - 224
    - 96
    - 79
    - 164
    - 246
    - 208
    - 128
    - 221
    - 161
    - 210
    - 176
    - 233
    - 108
    - 113
    - 91
    candidate_ids:
    - 176
    - 224
    - 96
    elector_ids:
    - 79
    - 164
    - 246
    - 208
    - 128
    - 221
    - 161
    - 210
    - 233
    - 108
    - 113
    - 91
    description: Medium group with 15 cardinals and 3 candidates
    ideology_balance:
      progressive: 5
      conservative: 5
      moderate: 5
  large:
    total_cardinals: 25
    cardinal_ids:
    - 224
    - 96
    - 79
    - 164
    - 246
    - 229
    - 194
    - 78
    - 208
    - 128
    - 221
    - 161
    - 210
    - 226
    - 74
    - 9
    - 176
    - 233
    - 108
    - 113
    - 91
    - 112
    - 153
    - 110
    - 111
    candidate_ids:
    - 176
    - 224
    - 96
    - 79
    - 164
    elector_ids:
    - 246
    - 229
    - 194
    - 78
    - 208
    - 128
    - 221
    - 161
    - 210
    - 226
    - 74
    - 9
    - 233
    - 108
    - 113
    - 91
    - 112
    - 153
    - 110
    - 111
    description: Large group with 25 cardinals and 5 candidates
    ideology_balance:
      progressive: 8
      conservative: 8
      moderate: 9
  xlarge:
    total_cardinals: 50
    cardinal_ids:
    - 224
    - 96
    - 79
    - 164
    - 246
    - 229
    - 194
    - 78
    - 66
    - 228
    - 213
    - 232
    - 251
    - 59
    - 94
    - 14
    - 208
    - 128
    - 221
    - 161
    - 210
    - 226
    - 74
    - 9
    - 33
    - 183
    - 202
    - 150
    - 69
    - 97
    - 103
    - 231
    - 176
    - 233
    - 108
    - 113
    - 91
    - 112
    - 153
    - 110
    - 111
    - 21
    - 166
    - 248
    - 45
    - 236
    - 68
    - 109
    - 149
    - 173
    candidate_ids:
    - 176
    - 224
    - 96
    - 79
    - 164
    - 246
    - 229
    elector_ids:
    - 194
    - 78
    - 66
    - 228
    - 213
    - 232
    - 251
    - 59
    - 94
    - 14
    - 208
    - 128
    - 221
    - 161
    - 210
    - 226
    - 74
    - 9
    - 33
    - 183
    - 202
    - 150
    - 69
    - 97
    - 103
    - 231
    - 233
    - 108
    - 113
    - 91
    - 112
    - 153
    - 110
    - 111
    - 21
    - 166
    - 248
    - 45
    - 236
    - 68
    - 109
    - 149
    - 173
    description: Xlarge group with 50 cardinals and 7 candidates
    ideology_balance:
      progressive: 16
      conservative: 16
      moderate: 18
  full:
    total_cardinals: 108
    cardinal_ids:
    - 2
    - 3
    - 4
    - 6
    - 8
    - 9
    - 13
    - 14
    - 21
    - 28
    - 30
    - 33
    - 37
    - 38
    - 39
    - 45
    - 49
    - 51
    - 52
    - 54
    - 56
    - 58
    - 59
    - 63
    - 65
    - 66
    - 68
    - 69
    - 74
    - 78
    - 79
    - 80
    - 82
    - 83
    - 87
    - 88
    - 90
    - 91
    - 94
    - 95
    - 96
    - 97
    - 99
    - 103
    - 108
    - 109
    - 110
    - 111
    - 112
    - 113
    - 118
    - 120
    - 122
    - 123
    - 124
    - 128
    - 131
    - 132
    - 136
    - 138
    - 142
    - 144
    - 145
    - 149
    - 150
    - 151
    - 152
    - 153
    - 157
    - 158
    - 160
    - 161
    - 164
    - 166
    - 171
    - 172
    - 173
    - 176
    - 182
    - 183
    - 192
    - 193
    - 194
    - 199
    - 201
    - 202
    - 204
    - 205
    - 206
    - 208
    - 210
    - 213
    - 216
    - 219
    - 221
    - 223
    - 224
    - 226
    - 228
    - 229
    - 231
    - 232
    - 233
    - 236
    - 243
    - 246
    - 248
    - 251
    candidate_ids:
    - 176
    - 224
    - 96
    - 79
    - 164
    - 246
    - 229
    - 194
    - 78
    - 233
    elector_ids:
    - 2
    - 3
    - 4
    - 6
    - 8
    - 9
    - 13
    - 14
    - 21
    - 28
    - 30
    - 33
    - 37
    - 38
    - 39
    - 45
    - 49
    - 51
    - 52
    - 54
    - 56
    - 58
    - 59
    - 63
    - 65
    - 66
    - 68
    - 69
    - 74
    - 80
    - 82
    - 83
    - 87
    - 88
    - 90
    - 91
    - 94
    - 95
    - 97
    - 99
    - 103
    - 108
    - 109
    - 110
    - 111
    - 112
    - 113
    - 118
    - 120
    - 122
    - 123
    - 124
    - 128
    - 131
    - 132
    - 136
    - 138
    - 142
    - 144
    - 145
    - 149
    - 150
    - 151
    - 152
    - 153
    - 157
    - 158
    - 160
    - 161
    - 166
    - 171
    - 172
    - 173
    - 182
    - 183
    - 192
    - 193
    - 199
    - 201
    - 202
    - 204
    - 205
    - 206
    - 208
    - 210
    - 213
    - 216
    - 219
    - 221
    - 223
    - 226
    - 228
    - 231
    - 232
    - 236
    - 243
    - 248
    - 251
    description: Full group with 108 cardinals and 10 candidates
    ideology_balance:
      progressive: 48
      conservative: 40
      moderate: 20
