output:
  logging:
    log_level: DEBUG
    performance_logging: true
  results:
    save_individual_votes: true
    save_discussion_transcripts: true
    save_agent_states: false
  visualization:
    auto_generate: true
    include_network_graphs: true
    reduction_method: tsne # Options: pca, tsne, umap (if umap library is installed)
    output_format: png # Options: png, svg, pdf
    dpi: 300
    tsne:
      perplexity: 30.0
      n_iter: 1000
      random_state: null # or an integer for reproducibility
    umap:
      n_neighbors: 15
      min_dist: 0.1
      metric: 'euclidean'
      random_state: null # or an integer for reproducibility
    pca:
      random_state: null # or an integer for reproducibility
    plot:
      target_type: 'stance' # or 'ideology'
      show_names: true
      show_initial_stances: true
      show_final_stances: true
      show_paths: true
      show_group_colors: true
      font_size: 8
      figure_size: [10.0, 8.0]
      colormap: 'viridis'
      path_alpha: 0.5
      path_linewidth: 1.0
      point_size: 50
      initial_stance_marker: 'o'
      final_stance_marker: 'X'
      intermediate_stance_marker: '.'
      candidate_marker: '*'
      non_candidate_marker: '.'
      candidate_color: 'red'
      non_candidate_color: 'blue'
      group_palette: 'Set2'
      stance_history_limit: null # or an integer to limit history points
