simulation:
  num_cardinals: 5
  discussion_group_size: 3
  max_election_rounds: 5
  discussion_length:
    min_words: 50
    max_words: 100
  voting:
    require_reasoning: true
    supermajority_threshold: 0.667
  enable_parallel_processing: true
  
  # Network-based grouping configuration
  grouping:
    room_size: 5
    rationality: 1.0  # 1.0 = fully utility-based, 0.0 = fully random
    penalty_weight: 0.1  # Weight for avoiding repeated pairings
    utility_weights:
      connection: 1.0
      ideology: 1.0  
      influence: 1.0
      interaction: 1.0
