simulation:
  num_cardinals: 5
  discussion_group_size: 3
  max_election_rounds: 5
  discussion_length:
    min_words: 50
    max_words: 100
  voting:
    require_reasoning: true
    supermajority_threshold: 0.667
  enable_parallel_processing: true
  
  # Network-based grouping configuration
  grouping:
    enabled: true
    method: "network_utility"  # Options: "random", "network_utility", "simple"
    group_size: 5
    utility_weights:
      connection: 1.0      # w1: connection strength weight
      ideology: 0.5        # w2: ideological proximity weight  
      influence: 0.2       # w3: influenceability weight
      interaction: 0.0     # w4: interaction term weight (for future use)
    stochasticity: 0.5     # 0.0 = deterministic, 1.0 = fully random
    leader_stochasticity: 0.1  # Randomness in leader selection
    seed: 42               # For reproducible results
