testing_groups:
  enabled: true
  active_group: small
  small:
    total_cardinals: 5
    cardinal_ids:
    - 164
    - 224
    - 10
    - 133
    - 251
    candidate_ids:
    - 164
    - 224
    description: Small testing group focusing on ideological diversity
    override_settings:
      num_cardinals: 5
      discussion_group_size: 3
      max_election_rounds: 8
      supermajority_threshold: 0.667
  medium:
    total_cardinals: 15
    cardinal_ids:
    - 164
    - 224
    - 10
    - 133
    - 251
    - 0
    - 155
    - 78
    - 23
    - 6
    - 54
    - 136
    - 187
    - 96
    - 109
    candidate_ids:
    - 164
    - 224
    - 10
    - 78
    description: Medium testing group with regional and theological balance
    override_settings:
      num_cardinals: 15
      discussion_group_size: 5
      max_election_rounds: 6
      supermajority_threshold: 0.667
  large:
    total_cardinals: 25
    cardinal_ids:
    - 164
    - 224
    - 10
    - 133
    - 251
    - 0
    - 155
    - 78
    - 23
    - 6
    - 54
    - 136
    - 187
    - 96
    - 109
    - 13
    - 173
    - 14
    - 147
    - 150
    - 208
    - 74
    - 66
    - 91
    - 176
    candidate_ids:
    - 164
    - 224
    - 10
    - 78
    - 208
    description: Large testing group with comprehensive global representation
    override_settings:
      num_cardinals: 25
      discussion_group_size: 5
      max_election_rounds: 10
      supermajority_threshold: 0.667
